/* The following code was generated by JFlex 1.4.3 on 30/05/14 2:39 */

package lexico_sintactico;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30/05/14 2:39 from the specification file
 * <tt>src/lexico_sintactico/Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\36\2\0\1\36\22\0\1\36\7\0\1\6\1\7"+
    "\1\0\1\15\1\5\3\0\1\1\11\2\1\0\1\4\1\14\1\12"+
    "\1\13\2\0\32\3\6\0\1\30\1\3\1\20\1\3\1\23\1\22"+
    "\1\35\1\33\1\16\2\3\1\34\1\31\1\17\1\21\1\27\1\3"+
    "\1\25\1\32\1\24\1\26\5\3\1\10\1\0\1\11\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\13\3\1\16"+
    "\1\17\1\20\1\21\14\3\1\22\5\3\1\23\27\3"+
    "\1\24\2\3\1\25\1\3\1\26\5\3\1\27\1\3"+
    "\1\30\1\3\1\31\6\3\1\32\1\33\1\34\1\35"+
    "\5\3\1\36\1\37\3\3\1\40\1\3\1\41\1\42"+
    "\4\3\1\43\1\44\1\3\1\45\1\46\1\3\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\37\0\76\0\135\0\37\0\37\0\37"+
    "\0\37\0\37\0\37\0\174\0\233\0\272\0\37\0\331"+
    "\0\370\0\u0117\0\u0136\0\u0155\0\u0174\0\u0193\0\u01b2\0\u01d1"+
    "\0\u01f0\0\u020f\0\u022e\0\37\0\37\0\37\0\u024d\0\u026c"+
    "\0\u028b\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\u0326\0\u0345\0\u0364"+
    "\0\u0383\0\u03a2\0\u03c1\0\u03e0\0\u03ff\0\u041e\0\u043d\0\u045c"+
    "\0\u047b\0\u049a\0\u04b9\0\u04d8\0\u04f7\0\u0516\0\u0535\0\u0554"+
    "\0\u0573\0\u0592\0\u05b1\0\u05d0\0\u05ef\0\u060e\0\u062d\0\u064c"+
    "\0\u066b\0\u068a\0\u06a9\0\u06c8\0\u06e7\0\u0706\0\u0725\0\u0744"+
    "\0\135\0\u0763\0\u0782\0\135\0\u07a1\0\135\0\u07c0\0\u07df"+
    "\0\u07fe\0\u081d\0\u083c\0\135\0\u085b\0\u087a\0\u0899\0\135"+
    "\0\u08b8\0\u08d7\0\u08f6\0\u0915\0\u0934\0\u0953\0\135\0\135"+
    "\0\135\0\135\0\u0972\0\u0991\0\u09b0\0\u09cf\0\u09ee\0\135"+
    "\0\135\0\u0a0d\0\u0a2c\0\u0a4b\0\135\0\u0a6a\0\135\0\135"+
    "\0\u0a89\0\u0aa8\0\u0ac7\0\u0ae6\0\135\0\135\0\u0b05\0\135"+
    "\0\135\0\u0b24\0\135";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\5"+
    "\1\21\1\5\1\22\1\23\1\24\1\25\1\5\1\26"+
    "\1\5\1\27\1\30\1\31\1\32\1\5\1\33\40\0"+
    "\2\4\35\0\3\5\12\0\20\5\13\0\1\34\36\0"+
    "\1\35\36\0\1\36\25\0\3\5\12\0\1\5\1\37"+
    "\16\5\2\0\3\5\12\0\1\40\2\5\1\41\14\5"+
    "\2\0\3\5\12\0\1\42\7\5\1\43\1\5\1\44"+
    "\5\5\2\0\3\5\12\0\1\5\1\45\14\5\1\46"+
    "\1\5\2\0\3\5\12\0\7\5\1\47\10\5\2\0"+
    "\3\5\12\0\5\5\1\50\12\5\2\0\3\5\12\0"+
    "\12\5\1\51\5\5\2\0\3\5\12\0\1\52\17\5"+
    "\2\0\3\5\12\0\1\53\17\5\2\0\3\5\12\0"+
    "\12\5\1\54\5\5\2\0\3\5\12\0\1\55\17\5"+
    "\37\0\1\33\1\0\3\5\12\0\1\56\17\5\2\0"+
    "\3\5\12\0\7\5\1\57\10\5\2\0\3\5\12\0"+
    "\16\5\1\60\1\5\2\0\3\5\12\0\1\5\1\61"+
    "\16\5\2\0\3\5\12\0\1\5\1\62\16\5\2\0"+
    "\3\5\12\0\16\5\1\63\1\5\2\0\3\5\12\0"+
    "\6\5\1\64\11\5\2\0\3\5\12\0\1\65\17\5"+
    "\2\0\3\5\12\0\10\5\1\66\7\5\2\0\3\5"+
    "\12\0\2\5\1\67\3\5\1\70\11\5\2\0\3\5"+
    "\12\0\7\5\1\71\10\5\2\0\3\5\12\0\5\5"+
    "\1\72\12\5\2\0\3\5\12\0\1\5\1\73\16\5"+
    "\2\0\3\5\12\0\2\5\1\74\11\5\1\75\3\5"+
    "\2\0\3\5\12\0\1\5\1\76\16\5\2\0\3\5"+
    "\12\0\2\5\1\77\15\5\2\0\3\5\12\0\2\5"+
    "\1\100\15\5\2\0\3\5\12\0\3\5\1\101\14\5"+
    "\2\0\3\5\12\0\2\5\1\102\11\5\1\103\3\5"+
    "\2\0\3\5\12\0\2\5\1\104\15\5\2\0\3\5"+
    "\12\0\14\5\1\105\3\5\2\0\3\5\12\0\3\5"+
    "\1\106\1\5\1\107\12\5\2\0\3\5\12\0\11\5"+
    "\1\110\6\5\2\0\3\5\12\0\5\5\1\111\12\5"+
    "\2\0\3\5\12\0\6\5\1\112\11\5\2\0\3\5"+
    "\12\0\3\5\1\113\14\5\2\0\3\5\12\0\12\5"+
    "\1\114\5\5\2\0\3\5\12\0\1\5\1\115\16\5"+
    "\2\0\3\5\12\0\3\5\1\116\14\5\2\0\3\5"+
    "\12\0\5\5\1\117\12\5\2\0\3\5\12\0\6\5"+
    "\1\120\11\5\2\0\3\5\12\0\5\5\1\121\12\5"+
    "\2\0\3\5\12\0\1\122\17\5\2\0\3\5\12\0"+
    "\10\5\1\123\7\5\2\0\3\5\12\0\7\5\1\124"+
    "\10\5\2\0\3\5\12\0\1\125\17\5\2\0\3\5"+
    "\12\0\1\126\17\5\2\0\3\5\12\0\1\127\17\5"+
    "\2\0\3\5\12\0\5\5\1\130\12\5\2\0\3\5"+
    "\12\0\1\5\1\131\16\5\2\0\3\5\12\0\7\5"+
    "\1\132\10\5\2\0\3\5\12\0\14\5\1\133\3\5"+
    "\2\0\3\5\12\0\12\5\1\134\5\5\2\0\3\5"+
    "\12\0\7\5\1\135\10\5\2\0\3\5\12\0\6\5"+
    "\1\136\11\5\2\0\3\5\12\0\7\5\1\137\10\5"+
    "\2\0\3\5\12\0\12\5\1\140\5\5\2\0\3\5"+
    "\12\0\12\5\1\141\5\5\2\0\3\5\12\0\3\5"+
    "\1\142\14\5\2\0\3\5\12\0\16\5\1\143\1\5"+
    "\2\0\3\5\12\0\2\5\1\144\15\5\2\0\3\5"+
    "\12\0\1\5\1\145\16\5\2\0\3\5\12\0\3\5"+
    "\1\146\14\5\2\0\3\5\12\0\2\5\1\147\15\5"+
    "\2\0\3\5\12\0\3\5\1\150\14\5\2\0\3\5"+
    "\12\0\5\5\1\151\12\5\2\0\3\5\12\0\1\5"+
    "\1\152\16\5\2\0\3\5\12\0\1\5\1\153\16\5"+
    "\2\0\3\5\12\0\7\5\1\154\10\5\2\0\3\5"+
    "\12\0\3\5\1\155\14\5\2\0\3\5\12\0\16\5"+
    "\1\156\1\5\2\0\3\5\12\0\3\5\1\157\14\5"+
    "\2\0\3\5\12\0\1\5\1\160\16\5\2\0\3\5"+
    "\12\0\5\5\1\161\12\5\2\0\3\5\12\0\17\5"+
    "\1\162\2\0\3\5\12\0\12\5\1\163\5\5\2\0"+
    "\3\5\12\0\12\5\1\164\5\5\2\0\3\5\12\0"+
    "\3\5\1\165\14\5\2\0\3\5\12\0\14\5\1\166"+
    "\3\5\2\0\3\5\12\0\10\5\1\167\7\5\2\0"+
    "\3\5\12\0\7\5\1\170\10\5\2\0\3\5\12\0"+
    "\14\5\1\171\3\5\2\0\3\5\12\0\16\5\1\172"+
    "\1\5\2\0\3\5\12\0\3\5\1\173\14\5\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2883];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\6\11\3\1\1\11\14\1\3\11"+
    "\135\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 98) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { return new Symbol(sym.MAYOR, new token(yycolumn, yyline, yytext()));
          }
        case 40: break;
        case 26: 
          { return new Symbol(sym.HACER, new token(yycolumn, yyline, yytext()));
          }
        case 41: break;
        case 39: 
          { return new Symbol(sym.RECTANGULO, new token(yycolumn, yyline, yytext()));
          }
        case 42: break;
        case 32: 
          { return new Symbol(sym.CIRCULO, new token(yycolumn, yyline, yytext()));
          }
        case 43: break;
        case 20: 
          { return new Symbol(sym.TRUE, new token(yycolumn, yyline, yytext()));
          }
        case 44: break;
        case 37: 
          { return new Symbol(sym.RETORNAR, new token(yycolumn, yyline, yytext()));
          }
        case 45: break;
        case 1: 
          { System.err.println("caracter invalido" + yytext() + "["+ yyline + ":"+ yycolumn + "]");
          }
        case 46: break;
        case 27: 
          { return new Symbol(sym.HASTA, new token(yycolumn, yyline, yytext()));
          }
        case 47: break;
        case 23: 
          { return new Symbol(sym.COLOR, new token(yycolumn, yyline, yytext()));
          }
        case 48: break;
        case 6: 
          { return new Symbol(sym.ABRIRPAR, new token(yycolumn, yyline, yytext()));
          }
        case 49: break;
        case 3: 
          { return new Symbol(sym.IDENTIFICADOR, new token(yycolumn, yyline, yytext()));
          }
        case 50: break;
        case 16: 
          { return new Symbol(sym.MAYORQUE, new token(yycolumn, yyline, yytext()));
          }
        case 51: break;
        case 8: 
          { return new Symbol(sym.ABRIRLLAV, new token(yycolumn, yyline, yytext()));
          }
        case 52: break;
        case 17: 
          { return new Symbol(sym.MENORQUE, new token(yycolumn, yyline, yytext()));
          }
        case 53: break;
        case 13: 
          { return new Symbol(sym.MAS, new token(yycolumn, yyline, yytext()));
          }
        case 54: break;
        case 22: 
          { return new Symbol(sym.SINO, new token(yycolumn, yyline, yytext()));
          }
        case 55: break;
        case 24: 
          { return new Symbol(sym.FINSI, new token(yycolumn, yyline, yytext()));
          }
        case 56: break;
        case 31: 
          { return new Symbol(sym.ELIPSE, new token(yycolumn, yyline, yytext()));
          }
        case 57: break;
        case 15: 
          { return new Symbol(sym.IGUAL, new token(yycolumn, yyline, yytext()));
          }
        case 58: break;
        case 18: 
          { return new Symbol(sym.SI, new token(yycolumn, yyline, yytext()));
          }
        case 59: break;
        case 2: 
          { return new Symbol(sym.VALINT, new token(yycolumn, yyline, yytext()));
          }
        case 60: break;
        case 38: 
          { return new Symbol(sym.MIENTRAS, new token(yycolumn, yyline, yytext()));
          }
        case 61: break;
        case 28: 
          { return new Symbol(sym.LINEA, new token(yycolumn, yyline, yytext()));
          }
        case 62: break;
        case 29: 
          { return new Symbol(sym.INICIO, new token(yycolumn, yyline, yytext()));
          }
        case 63: break;
        case 9: 
          { return new Symbol(sym.CIERRALLAV, new token(yycolumn, yyline, yytext()));
          }
        case 64: break;
        case 21: 
          { return new Symbol(sym.PARA, new token(yycolumn, yyline, yytext()));
          }
        case 65: break;
        case 4: 
          { return new Symbol(sym.PUNTOCOMA, new token(yycolumn, yyline, yytext()));
          }
        case 66: break;
        case 12: 
          { return new Symbol(sym.MENOR, new token(yycolumn, yyline, yytext()));
          }
        case 67: break;
        case 33: 
          { return new Symbol(sym.FINSINO, new token(yycolumn, yyline, yytext()));
          }
        case 68: break;
        case 5: 
          { return new Symbol(sym.COMA, new token(yycolumn, yyline, yytext()));
          }
        case 69: break;
        case 19: 
          { return new Symbol(sym.FIN, new token(yycolumn, yyline, yytext()));
          }
        case 70: break;
        case 30: 
          { return new Symbol(sym.ENTERO, new token(yycolumn, yyline, yytext()));
          }
        case 71: break;
        case 10: 
          { return new Symbol(sym.ASIGNACION, new token(yycolumn, yyline, yytext()));
          }
        case 72: break;
        case 35: 
          { return new Symbol(sym.FINCICLO, new token(yycolumn, yyline, yytext()));
          }
        case 73: break;
        case 34: 
          { return new Symbol(sym.FUNCION, new token(yycolumn, yyline, yytext()));
          }
        case 74: break;
        case 25: 
          { return new Symbol(sym.FALSE, new token(yycolumn, yyline, yytext()));
          }
        case 75: break;
        case 36: 
          { return new Symbol(sym.ENTONCES, new token(yycolumn, yyline, yytext()));
          }
        case 76: break;
        case 7: 
          { return new Symbol(sym.CERRARPAR, new token(yycolumn, yyline, yytext()));
          }
        case 77: break;
        case 14: 
          { 
          }
        case 78: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
