
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 30 16:20:04 GMT-05:00 2014
//----------------------------------------------------

package lexico_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VALINT = 37;
  public static final int ENTERO = 8;
  public static final int SI = 22;
  public static final int FUNCION = 15;
  public static final int FINCICLO = 21;
  public static final int ENTONCES = 23;
  public static final int PUNTOCOMA = 2;
  public static final int FIN = 7;
  public static final int HASTA = 19;
  public static final int IDENTIFICADOR = 38;
  public static final int MAYORQUE = 28;
  public static final int IGUAL = 25;
  public static final int SINO = 30;
  public static final int MIENTRAS = 35;
  public static final int CIRCULO = 10;
  public static final int CIERRALLAV = 17;
  public static final int EOF = 0;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int ABRIRLLAV = 16;
  public static final int MENOR = 27;
  public static final int ASIGNACION = 14;
  public static final int COLOR = 13;
  public static final int MENORQUE = 29;
  public static final int MAYOR = 26;
  public static final int ELIPSE = 12;
  public static final int RECTANGULO = 9;
  public static final int FINSINO = 31;
  public static final int HACER = 20;
  public static final int PARA = 18;
  public static final int RETORNAR = 32;
  public static final int INICIO = 6;
  public static final int FALSE = 34;
  public static final int FINSI = 24;
  public static final int ABRIRPAR = 4;
  public static final int LINEA = 11;
  public static final int MAS = 36;
  public static final int CERRARPAR = 5;
}

